<template>
  <a-select
    v-model:value="inputValue"
    :options="cityOptions"
    placeholder="选择目的地"
    style="width: 100%"
    show-search
    :filter-option="filterOption"
    @change="handleChange"
  />
</template>

<script setup lang="ts">
import { ref } from 'vue'

const props = defineProps<{ value: string }>()
const emit = defineEmits<{
  'update:value': [value: string]
  'destination-confirmed': [value: string]
}>()

const inputValue = ref<string>(props.value || '南京')

const cityOptions = [
  // 直辖市
  { value: '北京', label: '北京' },
  { value: '上海', label: '上海' },
  { value: '天津', label: '天津' },
  { value: '重庆', label: '重庆' },

  // 华东
  { value: '南京', label: '南京' },
  { value: '苏州', label: '苏州' },
  { value: '无锡', label: '无锡' },
  { value: '常州', label: '常州' },
  { value: '扬州', label: '扬州' },
  { value: '镇江', label: '镇江' },
  { value: '南通', label: '南通' },
  { value: '徐州', label: '徐州' },
  { value: '连云港', label: '连云港' },
  { value: '淮安', label: '淮安' },
  { value: '盐城', label: '盐城' },
  { value: '杭州', label: '杭州' },
  { value: '宁波', label: '宁波' },
  { value: '温州', label: '温州' },
  { value: '嘉兴', label: '嘉兴' },
  { value: '湖州', label: '湖州' },
  { value: '绍兴', label: '绍兴' },
  { value: '金华', label: '金华' },
  { value: '衢州', label: '衢州' },
  { value: '舟山', label: '舟山' },
  { value: '台州', label: '台州' },
  { value: '丽水', label: '丽水' },
  { value: '合肥', label: '合肥' },
  { value: '黄山', label: '黄山' },
  { value: '宏村', label: '宏村' },
  { value: '西递', label: '西递' },
  { value: '西塘', label: '西塘' },
  { value: '乌镇', label: '乌镇' },
  { value: '周庄', label: '周庄' },
  { value: '千岛湖', label: '千岛湖' },
  { value: '普陀山', label: '普陀山' },
  { value: '雁荡山', label: '雁荡山' },
  { value: '庐山', label: '庐山' },
  { value: '井冈山', label: '井冈山' },
  { value: '龙虎山', label: '龙虎山' },
  { value: '三清山', label: '三清山' },
  { value: '武夷山', label: '武夷山' },
  { value: '泉州', label: '泉州' },
  { value: '福州', label: '福州' },
  { value: '厦门', label: '厦门' },
  { value: '漳州', label: '漳州' },
  { value: '莆田', label: '莆田' },
  { value: '宁德', label: '宁德' },
  { value: '龙岩', label: '龙岩' },
  { value: '南平', label: '南平' },
  { value: '三明', label: '三明' },
  { value: '青岛', label: '青岛' },
  { value: '济南', label: '济南' },
  { value: '烟台', label: '烟台' },
  { value: '威海', label: '威海' },
  { value: '潍坊', label: '潍坊' },
  { value: '淄博', label: '淄博' },
  { value: '泰安', label: '泰安' },
  { value: '曲阜', label: '曲阜' },
  { value: '蓬莱', label: '蓬莱' },
  { value: '日照', label: '日照' },

  // 华南
  { value: '广州', label: '广州' },
  { value: '深圳', label: '深圳' },
  { value: '珠海', label: '珠海' },
  { value: '汕头', label: '汕头' },
  { value: '佛山', label: '佛山' },
  { value: '东莞', label: '东莞' },
  { value: '中山', label: '中山' },
  { value: '惠州', label: '惠州' },
  { value: '潮州', label: '潮州' },
  { value: '揭阳', label: '揭阳' },
  { value: '湛江', label: '湛江' },
  { value: '江门', label: '江门' },
  { value: '茂名', label: '茂名' },
  { value: '肇庆', label: '肇庆' },
  { value: '梅州', label: '梅州' },
  { value: '清远', label: '清远' },
  { value: '韶关', label: '韶关' },
  { value: '阳江', label: '阳江' },
  { value: '河源', label: '河源' },
  { value: '汕尾', label: '汕尾' },
  { value: '云浮', label: '云浮' },
  { value: '南宁', label: '南宁' },
  { value: '桂林', label: '桂林' },
  { value: '北海', label: '北海' },
  { value: '阳朔', label: '阳朔' },
  { value: '柳州', label: '柳州' },
  { value: '梧州', label: '梧州' },
  { value: '钦州', label: '钦州' },
  { value: '防城港', label: '防城港' },
  { value: '玉林', label: '玉林' },
  { value: '百色', label: '百色' },
  { value: '三亚', label: '三亚' },
  { value: '海口', label: '海口' },
  { value: '琼海', label: '琼海' },
  { value: '万宁', label: '万宁' },
  { value: '五指山', label: '五指山' },
  { value: '文昌', label: '文昌' },
  { value: '儋州', label: '儋州' },

  // 华中
  { value: '武汉', label: '武汉' },
  { value: '宜昌', label: '宜昌' },
  { value: '襄阳', label: '襄阳' },
  { value: '荆州', label: '荆州' },
  { value: '恩施', label: '恩施' },
  { value: '十堰', label: '十堰' },
  { value: '黄石', label: '黄石' },
  { value: '长沙', label: '长沙' },
  { value: '张家界', label: '张家界' },
  { value: '凤凰', label: '凤凰' },
  { value: '岳阳', label: '岳阳' },
  { value: '衡阳', label: '衡阳' },
  { value: '株洲', label: '株洲' },
  { value: '湘潭', label: '湘潭' },
  { value: '常德', label: '常德' },
  { value: '益阳', label: '益阳' },
  { value: '郴州', label: '郴州' },
  { value: '怀化', label: '怀化' },
  { value: '娄底', label: '娄底' },
  { value: '邵阳', label: '邵阳' },
  { value: '永州', label: '永州' },
  { value: '郑州', label: '郑州' },
  { value: '洛阳', label: '洛阳' },
  { value: '开封', label: '开封' },
  { value: '安阳', label: '安阳' },
  { value: '登封', label: '登封' },
  { value: '少林寺', label: '少林寺' },
  { value: '南阳', label: '南阳' },
  { value: '许昌', label: '许昌' },
  { value: '信阳', label: '信阳' },
  { value: '新乡', label: '新乡' },

  // 西南
  { value: '成都', label: '成都' },
  { value: '乐山', label: '乐山' },
  { value: '峨眉山', label: '峨眉山' },
  { value: '都江堰', label: '都江堰' },
  { value: '青城山', label: '青城山' },
  { value: '九寨沟', label: '九寨沟' },
  { value: '黄龙', label: '黄龙' },
  { value: '稻城', label: '稻城' },
  { value: '亚丁', label: '亚丁' },
  { value: '色达', label: '色达' },
  { value: '康定', label: '康定' },
  { value: '泸沽湖', label: '泸沽湖' },
  { value: '西昌', label: '西昌' },
  { value: '宜宾', label: '宜宾' },
  { value: '自贡', label: '自贡' },
  { value: '阆中', label: '阆中' },
  { value: '广元', label: '广元' },
  { value: '南充', label: '南充' },
  { value: '绵阳', label: '绵阳' },
  { value: '重庆', label: '重庆' },
  { value: '武隆', label: '武隆' },
  { value: '大足', label: '大足' },
  { value: '昆明', label: '昆明' },
  { value: '大理', label: '大理' },
  { value: '丽江', label: '丽江' },
  { value: '香格里拉', label: '香格里拉' },
  { value: '西双版纳', label: '西双版纳' },
  { value: '腾冲', label: '腾冲' },
  { value: '瑞丽', label: '瑞丽' },
  { value: '曲靖', label: '曲靖' },
  { value: '玉溪', label: '玉溪' },
  { value: '普洱', label: '普洱' },
  { value: '红河', label: '红河' },
  { value: '文山', label: '文山' },
  { value: '拉萨', label: '拉萨' },
  { value: '日喀则', label: '日喀则' },
  { value: '林芝', label: '林芝' },
  { value: '山南', label: '山南' },
  { value: '昌都', label: '昌都' },
  { value: '那曲', label: '那曲' },
  { value: '阿里', label: '阿里' },
  { value: '贵阳', label: '贵阳' },
  { value: '遵义', label: '遵义' },
  { value: '黄果树', label: '黄果树' },
  { value: '梵净山', label: '梵净山' },
  { value: '西江千户苗寨', label: '西江千户苗寨' },
  { value: '镇远', label: '镇远' },
  { value: '荔波', label: '荔波' },
  { value: '安顺', label: '安顺' },
  { value: '兴义', label: '兴义' },
  { value: '铜仁', label: '铜仁' },
  { value: '六盘水', label: '六盘水' },

  // 西北
  { value: '西安', label: '西安' },
  { value: '华山', label: '华山' },
  { value: '宝鸡', label: '宝鸡' },
  { value: '延安', label: '延安' },
  { value: '汉中', label: '汉中' },
  { value: '榆林', label: '榆林' },
  { value: '咸阳', label: '咸阳' },
  { value: '兰州', label: '兰州' },
  { value: '敦煌', label: '敦煌' },
  { value: '嘉峪关', label: '嘉峪关' },
  { value: '张掖', label: '张掖' },
  { value: '武威', label: '武威' },
  { value: '天水', label: '天水' },
  { value: '平凉', label: '平凉' },
  { value: '酒泉', label: '酒泉' },
  { value: '西宁', label: '西宁' },
  { value: '青海湖', label: '青海湖' },
  { value: '格尔木', label: '格尔木' },
  { value: '玉树', label: '玉树' },
  { value: '茶卡盐湖', label: '茶卡盐湖' },
  { value: '德令哈', label: '德令哈' },
  { value: '乌鲁木齐', label: '乌鲁木齐' },
  { value: '吐鲁番', label: '吐鲁番' },
  { value: '喀什', label: '喀什' },
  { value: '伊犁', label: '伊犁' },
  { value: '那拉提', label: '那拉提' },
  { value: '赛里木湖', label: '赛里木湖' },
  { value: '喀纳斯', label: '喀纳斯' },
  { value: '禾木', label: '禾木' },
  { value: '可可托海', label: '可可托海' },
  { value: '阿勒泰', label: '阿勒泰' },
  { value: '布尔津', label: '布尔津' },
  { value: '哈密', label: '哈密' },
  { value: '克拉玛依', label: '克拉玛依' },
  { value: '库尔勒', label: '库尔勒' },
  { value: '阿克苏', label: '阿克苏' },
  { value: '和田', label: '和田' },
  { value: '银川', label: '银川' },
  { value: '中卫', label: '中卫' },
  { value: '吴忠', label: '吴忠' },
  { value: '石嘴山', label: '石嘴山' },
  { value: '固原', label: '固原' },

  // 华北
  { value: '哈尔滨', label: '哈尔滨' },
  { value: '漠河', label: '漠河' },
  { value: '雪乡', label: '雪乡' },
  { value: '亚布力', label: '亚布力' },
  { value: '五大连池', label: '五大连池' },
  { value: '镜泊湖', label: '镜泊湖' },
  { value: '齐齐哈尔', label: '齐齐哈尔' },
  { value: '牡丹江', label: '牡丹江' },
  { value: '佳木斯', label: '佳木斯' },
  { value: '伊春', label: '伊春' },
  { value: '长春', label: '长春' },
  { value: '吉林', label: '吉林' },
  { value: '延吉', label: '延吉' },
  { value: '长白山', label: '长白山' },
  { value: '珲春', label: '珲春' },
  { value: '集安', label: '集安' },
  { value: '松原', label: '松原' },
  { value: '通化', label: '通化' },
  { value: '沈阳', label: '沈阳' },
  { value: '大连', label: '大连' },
  { value: '丹东', label: '丹东' },
  { value: '本溪', label: '本溪' },
  { value: '鞍山', label: '鞍山' },
  { value: '抚顺', label: '抚顺' },
  { value: '锦州', label: '锦州' },
  { value: '营口', label: '营口' },
  { value: '呼和浩特', label: '呼和浩特' },
  { value: '包头', label: '包头' },
  { value: '鄂尔多斯', label: '鄂尔多斯' },
  { value: '呼伦贝尔', label: '呼伦贝尔' },
  { value: '满洲里', label: '满洲里' },
  { value: '赤峰', label: '赤峰' },
  { value: '通辽', label: '通辽' },
  { value: '锡林浩特', label: '锡林浩特' },
  { value: '阿尔山', label: '阿尔山' },
  { value: '太原', label: '太原' },
  { value: '平遥', label: '平遥' },
  { value: '大同', label: '大同' },
  { value: '五台山', label: '五台山' },
  { value: '晋中', label: '晋中' },
  { value: '临汾', label: '临汾' },
  { value: '运城', label: '运城' },
  { value: '长治', label: '长治' },
  { value: '吕梁', label: '吕梁' },
  { value: '石家庄', label: '石家庄' },
  { value: '保定', label: '保定' },
  { value: '承德', label: '承德' },
  { value: '秦皇岛', label: '秦皇岛' },
  { value: '唐山', label: '唐山' },
  { value: '邯郸', label: '邯郸' },
  { value: '张家口', label: '张家口' },
  { value: '沧州', label: '沧州' },
  { value: '廊坊', label: '廊坊' },
  { value: '衡水', label: '衡水' },
  { value: '邢台', label: '邢台' },
]

function filterOption(input: string, option: any) {
  return option.value.toLowerCase().includes(input.toLowerCase())
}

function handleChange(v: string) {
  inputValue.value = v
  emit('update:value', v)
  emit('destination-confirmed', v)
}
</script>